# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_aiml_gke_model_armor_vllm_gemma_deployment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-gemma-deployment
spec:
      replicas: 1
      selector:
        matchLabels:
          app: gemma-server
      template:
        metadata:
          labels:
            app: gemma-server
            ai.gke.io/model: gemma-7b
            ai.gke.io/inference-server: vllm
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                -   matchExpressions:
                  -   key: cloud.google.com/gke-accelerator
                    operator: In
                    values:
                    -   nvidia-l4
              containers:
              -   name: inference-server
                image: us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20250801_0916_RC01
                resources:
                  requests:
                    cpu: "2"
                    memory: "25Gi"
                    ephemeral-storage: "25Gi"
                    nvidia.com/gpu: 2
                  limits:
                    cpu: "2"
                    memory: "25Gi"
                    ephemeral-storage: "25Gi"
                    nvidia.com/gpu: 2
                command: ["python3", "-m", "vllm.entrypoints.api_server"]
                args:
                -   --model=/models/gemma-7b
                -   --tensor-parallel-size=2
                env:
                -   name: MODEL_ID
                  value: /models/gemma-7b
                volumeMounts:
                -   mountPath: /dev/shm
                  name: dshm
                -   mountPath: /models
                  name: gemma-7b
              volumes:
              -   name: dshm
                emptyDir:
                    medium: Memory
              -   name: gemma-7b
                persistentVolumeClaim:
                  claimName: hdml-static-pvc
# [END gke_aiml_gke_model_armor_vllm_gemma_deployment]
